autoInstallPeers: true
catalogMode: prefer
cleanupUnusedCatalogs: true
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
verifyDepsBeforeRun: prompt

packages:
  - apps/*
  - packages/*
catalog:
  '@unocss/core': ^66.7.4
  '@unocss/eslint-plugin': ^66.7.4
  unocss: ^66.7.4
  unocss-preset-animations: ^1.3.0
  '@vueuse/motion': ^3.0.3
  md-editor-v3: ^6.5.6
  prettier: ^3.9.6
  '@tiptap/extension-table': ^3.30.1
  '@tiptap/extension-image': ^3.30.1
  '@tiptap/extension-find-and-replace': ^3.30.1
  '@tiptap/pm': ^3.30.1
  sanitize-html: ^2.17.7
  '@types/sanitize-html': ^2.16.1
  '@domternal/extension-image': ^0.15.0
  '@domternal/extension-details': ^0.15.0
  '@tailwindcss/typography': ^0.5.20
  jit-viewer: ^1.5.0
  vue-files-preview: ^1.0.43
allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  canvas: true
  core-js: true
  es5-ext: false
  esbuild: true
  simple-git-hooks: true
  vue-demi: true

overrides:
  emittery: ^0.13.1
  highlight.js: ^11.12.0
  '@tiptap/pm': 3.30.1
